config/routes.rb
Gsbg::Application.routes.draw do

  resources :line_items

  resources :carts

  get '/store' => 'store#index', as: :store_index
  devise_for :users, path_names: { 
                      :sign_in => 'login',
                      :sign_out => 'logout',
                      :sign_up => 'register' 
  }
  resources :shows
  resources :pages
  resources :press_items
  resources :products
  get 'press' => 'press_items#index', as: :press_index
  get ':id' => 'pages#show', as: :show_page

  root :to => "home#index"

  

end

app/views/pages/_form.html.erb
<%= simple_form_for @page, html: { class: "large-12 columns page-form" } do |f| %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.button :submit, class: "radius success" %>
<% end %>

app/views/pages/create.html.erb
<h1>Pages#create</h1>
<p>Find me in app/views/pages/create.html.erb</p>

app/views/pages/delete.html.erb
<h1>Pages#delete</h1>
<p>Find me in app/views/pages/delete.html.erb</p>

app/views/pages/edit.html.erb
<div class="row">
  <h1>Pages#edit</h1>
  <%= render 'form' %>
</div>

app/views/pages/new.html.erb
<h1>new page</h1>
<%= render 'form' %>

app/views/pages/show.html.erb
<div class="row">
  <div class="large-8 columns">
    <h2><%= @page.title %></h2>
    <div id="page-body">
      <%= simple_format @page.body %>
    </div>
    <div class="action">
      <%= link_to "Edit", edit_page_path(@page), class: "button" %>
    </div>
  </div>
  <div class="large-4 columns">
    <p>
    Tiramisu cookie topping candy canes chocolate marshmallow bear claw dessert. Gingerbread bear claw liquorice sweet marshmallow jujubes oat cake chocolate bar soufflé. Liquorice fruitcake lollipop danish pie liquorice donut. Unerdwear.com icing pie toffee carrot cake donut. Macaroon sesame snaps applicake. Bonbon marshmallow danish halvah toffee bonbon candy chocolate cake candy. Donut gummi bears bonbon danish brownie sugar plum gummi bears chocolate bar jelly-o. Gummi bears candy danish tootsie roll lollipop cotton candy jujubes. Jelly-o jelly-o sugar plum danish.
    </p>
    <p>
    Cheesecake cotton candy muffin jelly-o ice cream chocolate cake. Carrot cake lollipop muffin liquorice. Dragée caramels danish bonbon sweet roll. Topping caramels cotton candy macaroon sweet cake marshmallow. Marshmallow biscuit dragée halvah. Gummies lemon drops marshmallow. Lemon drops danish cookie tart tiramisu.
    </p>
  </div>
</div>

app/views/pages/update.html.erb
<h1>Pages#update</h1>
<p>Find me in app/views/pages/update.html.erb</p>