config/routes.rb
Gsbg::Application.routes.draw do

  resources :line_items

  resources :carts

  get '/store' => 'store#index', as: :store_index
  devise_for :users, path_names: { 
                      :sign_in => 'login',
                      :sign_out => 'logout',
                      :sign_up => 'register' 
  }
  resources :shows
  resources :pages
  resources :press_items
  resources :products
  get 'press' => 'press_items#index', as: :press_index
  get ':id' => 'pages#show', as: :show_page

  root :to => "home#index"

  

end

app/views/layouts/_admin_nav.html.erb
<div class="contain-to-grid">
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name"></li>
    </ul>
  <% if current_user.is_admin %>
    <section class="top-bar-section">
    <ul class="right">
      <li><%= link_to "New show", new_show_path %></li>
      <li><%= link_to "New page", new_page_path %></li>
      <li><%= link_to "New press item", new_press_item_path %></li>
      <li><%= link_to "New merch item", new_product_path %></li>
      <li><%= link_to "Log out", destroy_user_session_path, data: { method: :delete } %></li>
    </ul>
    </section>
  <% end %>
  </nav>
</div>

app/views/layouts/_main_nav.html.erb
  <div class="large-3 columns">
    <nav id="main"
    <ul>
      <li><%= link_to "Home", root_path %></li>          
      <li><%= link_to "Listen", "#" %></li>
      <li><%= link_to "Tour", shows_path %></li>
      <li><%= link_to "Band", "/band" %></li>
      <li><%= link_to "Store", store_index_path %></li>
      <li><%= link_to "Press", press_index_path %></li>
      <li><%= link_to "Media", "#" %></li>
      <li><%= link_to "Contact", "#" %></li>
    </ul>
    </nav>
  </div>

app/views/layouts/_nav.html.erb
<div class="contain-to-grid">
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name"></li>
    </ul>
  <% if current_user.is_admin %>
    <section class="top-bar-section">
    <ul class="right">
      <li><%= link_to "New show", new_show_path %></li>
      <li><%= link_to "New page", new_page_path %></li>
      <li><%= link_to "New press item", new_press_item_path %></li>
    </ul>
    </section>
  <% end %>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header id="header">
    <% if current_user %>
      <%= render 'layouts/admin_nav' %>
    <% end %>
      <div class="row">
        <div id="logo">
          <%= link_to content_tag(:h1, "Greensky Bluegrass", class: "column large-centered"), root_path %>
        </div>
      </div>
    </header>
    <div id="main">
      <div class="row">
        <% flash.each do |key, value| %>
          <div class='alert-box large-12 column <%= key %>' data-alert>
            <%= value %>
            <a href="#" class="close">&times;</a>
          </div>
        <% end %>
      </div>

      <div class="row">
        <%= render 'layouts/main_nav' %>
        <div class="large-9 columns">
          <%= yield %>
        </div>
      </div>
    </div>

    <footer id="footer">

    </footer>
    <%= javascript_include_tag "application" %>
  </body>
</html>